name: Fortify SAST Scan

on:
  push:
    branches: [ "main" ]

jobs:
  Fortify-SAST:
    # 指定使用你在地端主機 A 設定的 Self-hosted Runner 標籤
    runs-on: fortify-scan-a 

    steps:
      # 步驟 1: 下載源碼
      - name: Checkout Code
        uses: actions/checkout@v4

    # 步驟 2: 執行 SAST 掃描 (Fortify SCA)
      - name: Fortify SCA Scan
        shell: cmd
        run: |
          sourceanalyzer -b eightball2 -clean
          sourceanalyzer -b eightball2 . 
          sourceanalyzer -b eightball2 -scan -f eightball2.fpr -sc classic

    # 步驟 3: 使用 fcli 登入並上傳 fpr 到主機 B (SSC)
      - name: Upload to SSC
        shell: powershell  # 指定使用 
        run: |
          # 登入 SSC
          fcli ssc session login --url http://192.168.11.128:8080/ssc --token 74a482c9-40df-4445-b94b-ddc06f9a2bd3
          # 上傳並建立版本 (假設 SSC 上已存在對應的應用程式版本 eightball:latest)
          fcli ssc artifact upload -f eightball2.fpr --appversion eightball2:1
